version : '3.7'

services:
    app:
        build:
            context: ./server
            args:
                BUILD_ENV: "${BUILD_ENV:-production}"
                OVERCOOKED_BRANCH: "${OVERCOOKED_BRANCH:-overcooked_ai_improvements}"
                GRAPHICS: "${GRAPHICS:-overcooked_graphics_v1.js}"
        environment: 
            FLASK_ENV: "${BUILD_ENV:-production}"
        ports:
            - "8080:5000"
        
