version : '3.7'

services:
    app:
        build: 
            context: ./server
            args:
                BUILD_ENV: production
        environment: 
            FLASK_ENV: production
        ports:
            - "8080:5000"
